import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, unlinkSync } from 'node:fs';

const toolchain = readFileSync('formal/lean-toolchain', 'utf8').trim();

// Boundary.lean writes formal/vectors.json when it is checked. Remove the file
// first so that its reappearance proves the generator ran, then require the
// regenerated bytes to equal the committed ones (the export is deterministic).
const VECTORS = 'formal/vectors.json';
const committed = existsSync(VECTORS) ? readFileSync(VECTORS, 'utf8') : null;
if (committed !== null) unlinkSync(VECTORS);

const result = spawnSync('lean', [`+${toolchain}`, 'formal/Boundary.lean'], {
  encoding: 'utf8', timeout: 60000,
});
process.stdout.write(result.stdout ?? '');
process.stderr.write(result.stderr ?? '');
assert.equal(result.status, 0, String(result.error ?? 'Lean check failed'));
const output = result.stdout;
assert.doesNotMatch(output, /sorryAx/);
const allowed = new Set(['propext', 'Quot.sound']);
for (const [, axioms] of output.matchAll(/depends on axioms: \[([^\]]*)\]/g)) {
  for (const axiom of axioms.split(',').map(x => x.trim()).filter(Boolean)) {
    assert.ok(allowed.has(axiom), `unapproved proof axiom ${axiom}`);
  }
}
for (const name of ['execution_has_recorded_allow', 'grants_execute_at_most_once', 'reuse_mutant_has_bad_trace']) {
  assert.ok(output.includes(`'Boundary.${name}'`), `missing axiom audit for ${name}`);
}

assert.ok(existsSync(VECTORS), `${VECTORS} was not regenerated by Lean`);
const regenerated = readFileSync(VECTORS, 'utf8');
const vectors = JSON.parse(regenerated);
assert.ok(Array.isArray(vectors.vectors) && vectors.vectors.length >= 7, 'too few shared vectors');
if (committed !== null) assert.equal(regenerated, committed, `${VECTORS} drifted from the committed export`);
console.log(`formal: ${VECTORS} regenerated by Lean, ${vectors.vectors.length} vectors, ${committed === null ? 'no prior copy' : 'byte-identical to the committed copy'}`);
